### ISSUE TITLE
Callback invoked while holding api_mutex, contrary to the header; plc_tag_lock() from a callback cannot be released by the application

### ISSUE THREAD

**Issue by spiel2001** [libplctag/libplctag#667]
### Summary

The header states that the tag event callback is invoked *outside* the internal tag mutex,
and says this makes it safe to call tag functions from the callback. In v2.7.1 the callback
is invoked *inside* `critical_block(tag->api_mutex)`. Two consequences follow, and the
second one bites anyone who takes the header's advice about multi-call sequences:

1. Any public API call made against that tag from another thread blocks for the full
   duration of the callback.
2. `plc_tag_lock()` called from the callback succeeds on the library's own helper thread,
   after which the application cannot release it: `plc_tag_unlock()` from the application's
   thread returns `PLCTAG_ERR_MUTEX_UNLOCK`.

I found this while auditing an application that extracts values with `plc_tag_get_*` from
the callback after `PLCTAG_EVENT_READ_COMPLETED`, and was about to add
`plc_tag_lock`/`plc_tag_unlock` bracketing exactly as the header recommends.

A self-contained test is attached. It uses only the public API, needs only the bundled
`ab_server`, and requires **no sanitizer**: both results are deterministic and measured in
milliseconds.

### What the header promises

From the `plc_tag_register_callback` documentation:

```
 * @warning The callback is called outside the internal tag mutex, allowing it to call
 *          tag functions safely. However, it is called in the context of the internal
 *          tag helper thread, not the client library thread(s). YOU are responsible for
 *          ensuring all client application data structures accessed by the callback are
 *          thread-safe.
```

And from `plc_tag_lock`, which is the documented tool for the situation a callback is in:

```
 * Lock the tag against use by other threads. Because operations on a tag are very
 * much asynchronous, actions like getting and extracting the data from a tag take
 * more than one API call. If more than one thread is using the same tag, then the
 * internal state of the tag will get broken and you will probably experience a
 * crash.
```

Read together, these tell a consumer to bracket a callback's `plc_tag_get_*` sequence with
`plc_tag_lock`/`plc_tag_unlock`. That is the advice the test shows to be unsafe.

### How to reproduce

```bash
# terminal 1
ab_server --plc=ControlLogix --path=1,0 --tag=TestDint:DINT[10]

# terminal 2
./callback_mutex_test              # claim 1
./callback_mutex_test --test-lock  # claim 2
```

The test's method: the callback sleeps 400 ms; another thread times a single
`plc_tag_get_int32()` on the same tag. A control arm times the identical call while an
ordinary thread sleeps 400 ms holding nothing, which proves the accessor is not simply slow
and that the harness can distinguish the two cases.

### Measured output, v2.7.1, uninstrumented RelWithDebInfo build, GCC 8.5, Linux x86-64

```
libplctag callback mutex test
  library version 2.7.1
  callback hold time 400 ms, blocked threshold 150 ms

control  : accessor took 0 ms while an unrelated thread slept 400 ms
test     : accessor took 400 ms while the callback slept 400 ms

RESULT: the callback holds the tag's internal mutex.
```

And the second claim:

```
--- plc_tag_lock() from inside the callback ---
  plc_tag_lock() on the callback thread returned: PLCTAG_STATUS_OK
  plc_tag_unlock() from the main thread returned: PLCTAG_ERR_MUTEX_UNLOCK
  The tag is locked by a thread the application does not own,
  and the application cannot release it.
```

0 ms versus 400 ms is the whole result. A trivial accessor that returns immediately when
nothing holds the tag blocks for the entire callback duration when a callback is running.

### Where it comes from in the source

`plc_tag_generic_handle_event_callbacks` in `src/libplctag/lib/lib.c`:

```c
void plc_tag_generic_handle_event_callbacks(plc_tag_p tag) {
    if(!tag) { return; }

    critical_block(tag->api_mutex) {
        /* Check the callback under the API mutex, not before: plc_tag_destroy() clears
         * the callback (and userdata) under this same mutex while tearing the tag down.
         ... */
        if(!tag->callback) { break; }
        ...
        if(tag->event_read_complete) {
            tag->callback(tag->tag_id, PLCTAG_EVENT_READ_COMPLETED, tag->event_read_complete_status, tag->userdata);
            ...
        }
    } /* end of API mutex critical area. */
}
```

The locking itself looks right, and the comment explains why it is necessary: destroy
clears the callback under the same mutex, so the check and the call belong inside it. The
defect is that the header still describes the older behavior.

For the second claim, `plc_tag_lock` takes `api_mutex` in order to take `ext_mutex`:

```c
    do {
        critical_block(tag->api_mutex) { rc = mutex_try_lock(tag->ext_mutex); }
        ...
    } while(rc == PLCTAG_ERR_MUTEX_LOCK);
```

Because `mutex_create` requests `PTHREAD_MUTEX_RECURSIVE`, calling this from the callback
does not deadlock on `api_mutex`, which is why the lock reports success. But `ext_mutex` is
now owned by the library's tickler or handler thread rather than by the application, and
`pthread_mutex_unlock` from a different thread fails for a recursive mutex, so the
application is left unable to unlock a tag it believes it locked.

### Why this matters beyond the documentation

Because the callback holds `api_mutex`, anything slow in a callback blocks that tag's API
calls process-wide rather than merely delaying callback dispatch. The header's existing "do
not perform blocking operations in the callback" warning is therefore stronger than it
reads, and worth restating in those terms.

There is a useful flip side worth documenting explicitly if it is intended: holding
`api_mutex` across the callback means a callback's `plc_tag_get_*` calls are already
excluded against `plc_tag_read`, `plc_tag_write`, `plc_tag_status`, and `plc_tag_abort` for
that tag. If that is a guarantee consumers can rely on, saying so removes the need for
`plc_tag_lock` on the callback path entirely, which is a simplification rather than a
burden.

### Suggested resolution

Whichever the intent, the header and the code should agree:

- **If holding `api_mutex` across the callback is intended**, update the
  `plc_tag_register_callback` and `plc_tag_register_callback_ex` documentation to say so,
  state which API calls are consequently safe from a callback, and add an explicit "do not
  call `plc_tag_lock` from a callback" warning. That one line would have prevented the
  whole investigation.
- **If it is not intended**, copying the callback pointer and userdata under the mutex and
  invoking outside it would preserve the destroy-race fix the comment describes, at the
  cost of the callback possibly running once after `plc_tag_destroy` clears it.
- Separately, consider having `plc_tag_lock` return an error when called from the callback
  thread, since a lock the caller cannot release is not a useful success.

Happy to test a patch or a doc change against the attached test.

### Aside, not a request: the vendored libyafl still will not build under the sanitizers

Mentioning this only so you know, not to ask for anything. It is unrelated to the issue
above and I am deliberately not opening a separate ticket for it, since it looks like
vendored third-party code you have limited freedom to change.

The `-static` half of #662 is genuinely fixed in v2.7.1: with
`-DUSE_THREAD_SANITIZERS=1 -DCMAKE_BUILD_TYPE=Debug` the tree configures and links with no
compiler wrapper, and the libyafl stack-direction probe now reports "Stack grows downward
(supported)" instead of failing configure. That was the part that blocked sanitizer testing,
and it no longer does.

What remains is that `src/vendor/libyafl/src/yafl.c` itself does not compile on GCC 8.5.
Under ThreadSanitizer it fails on the fiber annotations, which no included header declares:

```
yafl.c:222:5: error: implicit declaration of function '__tsan_switch_to_fiber' [-Werror=implicit-function-declaration]
yafl.c:271:23: error: assignment to 'void *' from 'int' makes pointer from integer without a cast [-Werror=int-conversion]
```

The `int-conversion` errors follow from the implicit declarations rather than being separate
defects. Under both TSAN and ASAN it also fails on:

```
yafl.c:295:79: error: 'MAP_ANONYMOUS' undeclared (first use in this function)
```

which needs `_GNU_SOURCE` or `_DEFAULT_SOURCE` on glibc, and the toolchain file sets
`-D__USE_POSIX=1 -D_XOPEN_SOURCE=700 -D_POSIX_C_SOURCE=200809L`, none of which exposes it.

None of this blocks using the library. `libplctag.so` does not link libyafl, confirmed by
its absence from the library's dynamic symbols, and both sanitizer builds produce
`libplctag.so`, `libplctag_static.a`, `ab_server`, and the header before stopping on this
target. The only practical cost is that `cmake --build` exits non-zero, so a packaging
script has to tolerate that or exclude the POC targets.

If it is ever worth a few minutes, excluding the libyafl POC targets when sanitizers are
enabled would make the sanitizer builds exit cleanly. Entirely your call, and I am happy to
leave it alone.

### Attached

`libplctag-callback-mutex-test.zip`: the test source, a `CMakeLists.txt`, a README with
the method and the measured numbers, and the two captured output files. CC0, so fold it
into the test suite if it is useful.

[libplctag-callback-mutex-test.zip](https://github.com/user-attachments/files/31664687/libplctag-callback-mutex-test.zip)

**Comment by kyle-github** [comment]
Thanks for filing this.  This is documentation bug.  This was a race condition that was "solved" by putting the callback call inside the mutex.  The race condition was that the application could call and remove the callback function and user data pointer just before the library thread called it.  I was able to track this down with TSan.  The actual bug is in the documentation.  I clearly have not looked at that part for a while!!!

I will be removing libyafl as a dependency. It was only for a proof of concept.  As I aimed for better embedded use I tried to limit the number of threads needed.  The fiber library did limit it, but it is still too large and more difficult to bound for completely bounded memory usage.

**Comment by kyle-github** [comment]
`plc_tag_lock()` and `plc_tag_unlock()` are for coordinating between application threads, not between application threads and library threads.  The internal API mutex is for that and is used transparently.  It is definitely confusing.  I added those functions a long time ago and I do not remember why.   I need to do a big documentation update.

**Comment by kyle-github** [comment]
Please check the documentation about callbacks to make sure that it is more clear.  Do I need to add more details?  Please let me know.
